name: CI Automation Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies for frontend
        working-directory: ./speed_frontend
        run: npm install --ignore-scripts

      - name: Build frontend
        working-directory: ./speed_frontend
        run: npm run build

      - name: Install dependencies for backend
        working-directory: ./speed_backend
        run: npm install --ignore-scripts

      - name: Build backend
        working-directory: ./speed_backend
        run: npm run build
